jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /ventacontable
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://venta-contable-do-user-7053223-0.b.db.ondigitalocean.com:25060/ventacontable
      username: venta-contable
      password: ventacontable
      hikari:
         poolName: pool
